-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) as 'YEAR', MONTH(S.SALES_DATE) as 'MONTH', U.GENDER as 'GENDER', COUNT(DISTINCT S.USER_ID) as 'USERS' 
FROM ONLINE_SALE S
JOIN USER_INFO U ON (S.USER_ID=U.USER_ID AND U.GENDER IS NOT NULL)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;